language: node_js
node_js:
  - stable
branches:
  only:
    - develop
install:
  - npm install
cache:
  directories:
    - node_modules
services:
-postgres
before-script:
-psql -c 'CREATE DATABASE Free-Mentors;' -U postgres
script:
  - npm test
after_success:
  - npm run coveralls